print("CCCCCCC    K      K")
print("C          K     k")
print("C          K    k")
print("C          K   k")
print("C          K  K")
print("C       *  K K")
print("C          K  K")
print("C          K   K")
print("C          K    K")
print("C          K     K")
print("CCCCCCC    K       K")
